version: 0.2 
phases: 
  pre_build: 
    commands: 
      - echo now pre_build
      - aws ecr get-login-password --region $SURVEY_AWS_REGION | docker login --username AWS --password-stdin $SURVEY_AWS_ACCOUNT_ID.$SURVEY_AWS_REGION.amazonaws.com
  build:
    commands:
      - echo now build
      - echo "docker build -t $SURVEY_IMAGE_REPO_NAME:$SURVEY_IMAGE_TAG --build-arg --build-arg STAGE_ENV=$STAGE_ENV DOCKER_NAME=$DOCKER_NAME ."
      - docker build -t $SURVEY_IMAGE_REPO_NAME:$SURVEY_IMAGE_TAG --build-arg STAGE_ENV=$STAGE_ENV --build-arg DOCKER_NAME=$DOCKER_NAME .
      - docker tag $SURVEY_IMAGE_REPO_NAME:$SURVEY_IMAGE_TAG $SURVEY_AWS_ACCOUNT_ID.$SURVEY_AWS_REGION.amazonaws.com/$SURVEY_IMAGE_REPO_NAME:$SURVEY_IMAGE_TAG
  post_build:
    commands:
      - echo now post_build
      - docker push $SURVEY_AWS_ACCOUNT_ID.$SURVEY_AWS_REGION.amazonaws.com/$SURVEY_IMAGE_REPO_NAME:$SURVEY_IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' $SURVEY_IMAGE_REPO_NAME $SURVEY_AWS_ACCOUNT_ID.$SURVEY_AWS_REGION.amazonaws.com/$SURVEY_IMAGE_REPO_NAME:$SURVEY_IMAGE_TAG > imagedefinitions.json
artifacts:
  files: 
    - imagedefinitions.json
    - appspec.yml
    - taskdef.json

